from __future__ import annotations

import hashlib
import json
import math
from datetime import datetime, timezone
from typing import Any

from app.database.athena_database import AthenaDatabase


class RecommendationProductionPromotionProtocolRepository:
    """Append-only registry for production-promotion protocols.

    Registration time is generated by the repository at persistence time. Callers
    cannot supply or backdate it. A protocol therefore cannot be retroactively
    presented as precommitted after its confirmation evidence already exists.
    """

    PROTOCOL_VERSION = "athena-production-promotion-protocol-v1"

    def __init__(self, database: AthenaDatabase | None = None) -> None:
        self._database = database if database is not None else AthenaDatabase()

    def initialize(self) -> None:
        self._database.initialize()
        with self._database.connect() as connection:
            connection.executescript(
                """
                CREATE TABLE IF NOT EXISTS athena_recommendation_production_promotion_protocols (
                    id INTEGER PRIMARY KEY AUTOINCREMENT,
                    protocol_id TEXT NOT NULL UNIQUE,
                    research_gate_fingerprint TEXT NOT NULL,
                    registered_at TEXT NOT NULL,
                    protocol_json TEXT NOT NULL,
                    protocol_fingerprint TEXT NOT NULL UNIQUE,
                    created_at TEXT NOT NULL
                );

                CREATE INDEX IF NOT EXISTS idx_production_promotion_protocol_gate
                ON athena_recommendation_production_promotion_protocols(
                    research_gate_fingerprint,
                    registered_at
                );
                """
            )

    def register(self, *, protocol_draft: dict[str, Any]) -> dict[str, Any]:
        """Persist a new immutable protocol with a repository-generated timestamp."""
        self.initialize()
        core = self._validated_draft(protocol_draft)
        registered_at = datetime.now(timezone.utc).isoformat()
        protocol = {
            **core,
            "registeredAt": registered_at,
        }
        protocol_fingerprint = self._fingerprint(protocol)
        protocol = {
            **protocol,
            "protocolFingerprint": protocol_fingerprint,
        }
        serialized = self._serialize(protocol)
        created_at = datetime.now(timezone.utc).isoformat()

        with self._database.connect() as connection:
            existing = connection.execute(
                """
                SELECT *
                FROM athena_recommendation_production_promotion_protocols
                WHERE protocol_id = ?
                """,
                (core["protocolId"],),
            ).fetchone()
            if existing is not None:
                record = self._row(existing)
                if record is None:
                    raise RuntimeError("No se pudo recuperar el protocolo existente.")
                if record["protocol"] != protocol:
                    raise ValueError(
                        "protocolId ya está registrado; los protocolos son inmutables."
                    )
                return record

            connection.execute(
                """
                INSERT INTO athena_recommendation_production_promotion_protocols (
                    protocol_id,
                    research_gate_fingerprint,
                    registered_at,
                    protocol_json,
                    protocol_fingerprint,
                    created_at
                ) VALUES (?, ?, ?, ?, ?, ?)
                """,
                (
                    core["protocolId"],
                    core["researchGateFingerprint"],
                    registered_at,
                    serialized,
                    protocol_fingerprint,
                    created_at,
                ),
            )
            row = connection.execute(
                """
                SELECT *
                FROM athena_recommendation_production_promotion_protocols
                WHERE protocol_id = ?
                """,
                (core["protocolId"],),
            ).fetchone()
        result = self._row(row)
        if result is None:
            raise RuntimeError("No se pudo recuperar el protocolo registrado.")
        return result

    def get(self, *, protocol_id: str) -> dict[str, Any] | None:
        self.initialize()
        normalized_id = self._non_empty_string(protocol_id, "protocol_id")
        with self._database.connect() as connection:
            row = connection.execute(
                """
                SELECT *
                FROM athena_recommendation_production_promotion_protocols
                WHERE protocol_id = ?
                """,
                (normalized_id,),
            ).fetchone()
        return self._row(row)

    def validate_record(self, record: dict[str, Any]) -> dict[str, Any]:
        if not isinstance(record, dict):
            raise ValueError("El registro de protocolo debe ser un objeto.")
        protocol_id = self._non_empty_string(record.get("protocol_id"), "protocol_id")
        gate = self._sha256(
            record.get("research_gate_fingerprint"), "research_gate_fingerprint"
        )
        registered_at = self._aware_iso(record.get("registered_at"), "registered_at")
        created_at = self._aware_iso(record.get("created_at"), "created_at")
        if created_at < registered_at:
            raise ValueError("created_at no puede preceder a registered_at.")

        protocol = record.get("protocol")
        if not isinstance(protocol, dict):
            raise ValueError("El registro carece de protocol válido.")
        if protocol.get("protocolId") != protocol_id:
            raise ValueError("El protocolo persistido cambió de protocolId.")
        if protocol.get("researchGateFingerprint") != gate:
            raise ValueError("El protocolo persistido cambió de research gate.")
        if self._aware_iso(protocol.get("registeredAt"), "registeredAt") != registered_at:
            raise ValueError("El protocolo persistido cambió su fecha de registro.")

        supplied_fingerprint = self._sha256(
            record.get("protocol_fingerprint"), "protocol_fingerprint"
        )
        if protocol.get("protocolFingerprint") != supplied_fingerprint:
            raise ValueError("El fingerprint persistido no coincide con el protocolo.")
        unsigned = dict(protocol)
        unsigned.pop("protocolFingerprint", None)
        expected_fingerprint = self._fingerprint(unsigned)
        if supplied_fingerprint != expected_fingerprint:
            raise ValueError("El protocolo fue modificado después de persistirse.")
        return record

    def _validated_draft(self, payload: dict[str, Any]) -> dict[str, Any]:
        if not isinstance(payload, dict):
            raise ValueError("protocol_draft debe ser un objeto.")
        forbidden = {"registeredAt", "protocolFingerprint"}.intersection(payload)
        if forbidden:
            raise ValueError(
                "registeredAt y protocolFingerprint los genera el registro; no pueden suministrarse."
            )
        if payload.get("artifactVersion") != self.PROTOCOL_VERSION:
            raise ValueError("Versión de protocolo de promoción no compatible.")
        protocol_id = self._non_empty_string(payload.get("protocolId"), "protocolId")
        research_gate = self._sha256(
            payload.get("researchGateFingerprint"), "researchGateFingerprint"
        )

        required = payload.get("requiredHorizons")
        if not isinstance(required, list) or not required:
            raise ValueError("requiredHorizons debe ser una lista no vacía.")
        horizons: list[int] = []
        for value in required:
            if isinstance(value, bool) or not isinstance(value, int) or value <= 0:
                raise ValueError("requiredHorizons sólo admite enteros positivos.")
            horizons.append(value)
        if len(set(horizons)) != len(horizons):
            raise ValueError("requiredHorizons no puede contener duplicados.")

        criteria_payload = payload.get("criteriaByHorizon")
        if not isinstance(criteria_payload, dict):
            raise ValueError("criteriaByHorizon es obligatorio.")
        criteria: dict[str, dict[str, Any]] = {}
        for horizon in horizons:
            key = str(horizon)
            item = criteria_payload.get(key)
            if not isinstance(item, dict):
                raise ValueError(f"Faltan criterios precomprometidos para {horizon} días.")
            sign_accuracy = self._bounded_float(
                item.get("minimumSignAccuracy"),
                "minimumSignAccuracy",
                0.0,
                1.0,
            )
            mse_improvement = self._finite_float(
                item.get("minimumRelativeMseImprovement"),
                "minimumRelativeMseImprovement",
            )
            beat_baseline = item.get("requireBeatZeroExcessMseBaseline")
            if not isinstance(beat_baseline, bool):
                raise ValueError("requireBeatZeroExcessMseBaseline debe ser booleano.")
            criteria[key] = {
                "minimumSignAccuracy": sign_accuracy,
                "minimumRelativeMseImprovement": mse_improvement,
                "requireBeatZeroExcessMseBaseline": beat_baseline,
            }

        return {
            "artifactVersion": self.PROTOCOL_VERSION,
            "protocolId": protocol_id,
            "researchGateFingerprint": research_gate,
            "requiredHorizons": horizons,
            "criteriaByHorizon": criteria,
        }

    def _row(self, row: Any) -> dict[str, Any] | None:
        if row is None:
            return None
        try:
            protocol = json.loads(str(row["protocol_json"]))
        except (TypeError, ValueError, json.JSONDecodeError) as exc:
            raise ValueError("protocol_json persistido no es válido.") from exc
        record = {
            "id": int(row["id"]),
            "protocol_id": str(row["protocol_id"]),
            "research_gate_fingerprint": str(row["research_gate_fingerprint"]),
            "registered_at": str(row["registered_at"]),
            "protocol": protocol,
            "protocol_fingerprint": str(row["protocol_fingerprint"]),
            "created_at": str(row["created_at"]),
        }
        return self.validate_record(record)

    def _serialize(self, value: object) -> str:
        try:
            return json.dumps(
                value,
                sort_keys=True,
                separators=(",", ":"),
                ensure_ascii=True,
                allow_nan=False,
            )
        except (TypeError, ValueError) as exc:
            raise ValueError("El protocolo contiene valores no serializables o no finitos.") from exc

    def _fingerprint(self, payload: dict[str, Any]) -> str:
        return hashlib.sha256(self._serialize(payload).encode("utf-8")).hexdigest()

    def _sha256(self, value: object, field: str) -> str:
        normalized = str(value or "").strip().lower()
        if len(normalized) != 64 or any(ch not in "0123456789abcdef" for ch in normalized):
            raise ValueError(f"{field} debe ser SHA-256 válido.")
        return normalized

    def _non_empty_string(self, value: object, field: str) -> str:
        parsed = str(value or "").strip()
        if not parsed:
            raise ValueError(f"{field} es obligatorio.")
        return parsed

    def _finite_float(self, value: object, field: str) -> float:
        try:
            parsed = float(value)
        except (TypeError, ValueError) as exc:
            raise ValueError(f"{field} debe ser numérico.") from exc
        if not math.isfinite(parsed):
            raise ValueError(f"{field} debe ser finito.")
        return parsed

    def _bounded_float(
        self, value: object, field: str, minimum: float, maximum: float
    ) -> float:
        parsed = self._finite_float(value, field)
        if parsed < minimum or parsed > maximum:
            raise ValueError(f"{field} debe estar entre {minimum} y {maximum}.")
        return parsed

    def _aware_iso(self, value: object, field: str) -> str:
        raw = self._non_empty_string(value, field)
        try:
            parsed = datetime.fromisoformat(raw.replace("Z", "+00:00"))
        except ValueError as exc:
            raise ValueError(f"{field} debe ser ISO-8601 válido.") from exc
        if parsed.tzinfo is None or parsed.utcoffset() is None:
            raise ValueError(f"{field} debe incluir zona horaria.")
        return parsed.astimezone(timezone.utc).isoformat()
