"""Verify an ATHENA database backup by restoring it into an isolated database.

This command never restores over the configured production database. For ATHENA
managed SQLite backups it also requires the integrity manifest generated by
DatabaseBackupService, so a copied/corrupted database cannot bypass the checksum
and schema-version gates merely because SQLite can open it.
"""

from __future__ import annotations

import argparse
import os
import sys
import tempfile
from pathlib import Path

BACKEND_ROOT = Path(__file__).resolve().parents[1]
if str(BACKEND_ROOT) not in sys.path:
    sys.path.insert(0, str(BACKEND_ROOT))

from app.database.athena_database import AthenaDatabase
from app.services.database_backup_service import DatabaseBackupService


def _verify_managed_sqlite_backup(source: Path) -> None:
    if not source.is_file():
        raise RuntimeError(f"Backup does not exist: {source}")

    manifest = DatabaseBackupService.manifest_path_for(source)
    if not manifest.is_file():
        raise RuntimeError(
            "ATHENA backup integrity manifest is missing; refusing to report recovery success"
        )

    # The service verifies manifest format, size, SHA-256, SQLite integrity and
    # schema version before creating an isolated restored copy.
    database = AthenaDatabase(source.parent / ".athena-recovery-verifier-source.db")
    service = DatabaseBackupService(database)
    service.verify_backup(source)

    with tempfile.TemporaryDirectory(prefix="athena-recovery-") as directory:
        result = service.run_restore_drill(
            source,
            working_directory=Path(directory),
        )
        if result.schema_version <= 0:
            raise RuntimeError("Restored ATHENA schema version is invalid")


def verify_backup(backup_path: Path, *, database_url: str | None = None) -> None:
    configured_url = (database_url or os.getenv("DATABASE_URL") or "").strip()
    if configured_url.startswith("sqlite") or backup_path.suffix.lower() in {
        ".db",
        ".sqlite",
        ".sqlite3",
    }:
        _verify_managed_sqlite_backup(backup_path)
        return
    raise RuntimeError(
        "Recovery verification is not implemented for this database backend; "
        "refusing to report success"
    )


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Verify that an ATHENA backup is actually restorable"
    )
    parser.add_argument("backup", type=Path, help="Backup artifact to verify")
    args = parser.parse_args(argv)
    try:
        verify_backup(args.backup)
    except Exception as exc:
        print(f"RECOVERY VERIFICATION FAILED: {exc}", file=sys.stderr)
        return 1
    print(f"RECOVERY VERIFIED: {args.backup}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
