from pathlib import Path

from fastapi.testclient import TestClient

import app.api.auth as auth_api
from app.main import app


client = TestClient(app)
_SECRET = "athena-test-secret-0123456789abcdef0123456789abcdef"
_EMAIL = "recovery-lifecycle@example.com"
_OTHER_EMAIL = "recovery-other@example.com"
_INITIAL_PASSWORD = "CorrectHorseBatteryStaple!"
_RESET_PASSWORD = "RecoveredHorseBatteryStaple!"
_OTHER_PASSWORD = "IndependentHorseBatteryStaple!"


class _CapturingMailer:
    def __init__(self) -> None:
        self.challenges = []

    def send(self, challenge) -> None:
        self.challenges.append(challenge)


def _configure(monkeypatch, tmp_path: Path, mailer: _CapturingMailer) -> None:
    monkeypatch.setenv("ATHENA_DATABASE_PATH", str(tmp_path / "athena.db"))
    monkeypatch.setenv("ATHENA_AUTH_SECRET", _SECRET)
    monkeypatch.setattr(auth_api, "_recovery_mailer", lambda: mailer)


def _register(email: str, password: str):
    return client.post(
        "/api/v1/auth/register",
        json={"email": email, "password": password},
    )


def _login(email: str, password: str):
    return client.post(
        "/api/v1/auth/token",
        data={"username": email, "password": password},
    )


def _me(token: str):
    return client.get(
        "/api/v1/auth/me",
        headers={"Authorization": f"Bearer {token}"},
    )


def test_password_recovery_is_one_time_revokes_sessions_and_isolates_other_accounts(
    monkeypatch,
    tmp_path: Path,
) -> None:
    """Prove the recovery security boundary through the public HTTP API.

    SMTP transport is deliberately replaced only to capture the challenge generated by
    the application. This test is engineering evidence for reset semantics, not evidence
    that a production mail provider accepted or delivered a message.
    """
    mailer = _CapturingMailer()
    _configure(monkeypatch, tmp_path, mailer)

    created = _register(_EMAIL, _INITIAL_PASSWORD)
    other_created = _register(_OTHER_EMAIL, _OTHER_PASSWORD)
    assert created.status_code == 201, created.text
    assert other_created.status_code == 201, other_created.text

    first_login = _login(_EMAIL, _INITIAL_PASSWORD)
    second_login = _login(_EMAIL, _INITIAL_PASSWORD)
    other_login = _login(_OTHER_EMAIL, _OTHER_PASSWORD)
    assert first_login.status_code == 200, first_login.text
    assert second_login.status_code == 200, second_login.text
    assert other_login.status_code == 200, other_login.text
    first_token = first_login.json()["access_token"]
    second_token = second_login.json()["access_token"]
    other_token = other_login.json()["access_token"]
    assert _me(first_token).status_code == 200
    assert _me(second_token).status_code == 200
    assert _me(other_token).status_code == 200

    requested = client.post(
        "/api/v1/auth/recovery/request",
        json={"email": _EMAIL},
    )
    assert requested.status_code == 202, requested.text
    assert len(mailer.challenges) == 1
    challenge = mailer.challenges[0]
    assert challenge.email == _EMAIL
    assert len(challenge.token) >= 32

    reset = client.post(
        "/api/v1/auth/recovery/reset",
        json={"token": challenge.token, "newPassword": _RESET_PASSWORD},
    )
    assert reset.status_code == 204, reset.text

    # A successful recovery is an all-session boundary for the recovered account.
    assert _me(first_token).status_code == 401
    assert _me(second_token).status_code == 401
    assert _login(_EMAIL, _INITIAL_PASSWORD).status_code == 401

    recovered_login = _login(_EMAIL, _RESET_PASSWORD)
    assert recovered_login.status_code == 200, recovered_login.text
    recovered_token = recovered_login.json()["access_token"]
    assert _me(recovered_token).status_code == 200

    # The exact recovery bearer is single-use even when replayed with another valid
    # candidate password.
    replay = client.post(
        "/api/v1/auth/recovery/reset",
        json={"token": challenge.token, "newPassword": _INITIAL_PASSWORD},
    )
    assert replay.status_code == 400, replay.text
    assert _login(_EMAIL, _RESET_PASSWORD).status_code == 200
    assert _login(_EMAIL, _INITIAL_PASSWORD).status_code == 401

    # Session-version rotation is scoped to the recovered identity only.
    assert _me(other_token).status_code == 200
    assert _login(_OTHER_EMAIL, _OTHER_PASSWORD).status_code == 200
